
export const OPEN_LOADING = "OPEN_LOADING";
export const CLOSE_LOADING = "CLOSE_LOADING";
export const POST_MESSAGE = "POST_MESSAGE";
export const GET_ALL_POST = "GET_ALL_POST";
export const GET_POST_COMMENTS = "GET_POST_COMMENTS";
export const GET_MY_POSTS = "GET_MY_POSTS";
export const GET_SINGLE_POST_DET ="GET_SINGLE_POST_DET";
export const GET_SINGLE_POST_SUCCES ="GET_SINGLE_POST_SUCCES";
export const RESET_SINGLE_POST_SUCCES = "RESET_SINGLE_POST_SUCCES";
export const RESET_POST_SUCESS  = "RESET_POST_SUCESS";
export const ALL_COMMENTS = "ALL_COMMENTS";
export const RESET_POST_COMMENTS = "RESET_POST_COMMENTS";
