
export const TOOGLE_DRAWER = "TOOGLE_DRAWER";
export const CLOSE_DRAWER = "CLOSE_DRAWER";
export const TOOGLE_MOBILE_FILLTER = "TOOGLE_MOBILE_FILLTER";
export const WINDOW_DRAWER = "WINDOW_DRAWER";
export const B2B_DRAWER = "B2B_DRAWER";
